### ISSUE TITLE
Using this causes Google Docs voice typing to behave as if the window is always out of focus

### ISSUE THREAD

**Issue by laminarturbulent** [brc-dd/visibilityChanger#1]
I tested this extension with Chrome 84 and when I try to use voice typing on Docs, it immediately stops recording when I click the microphone.

**Comment by brc-dd** [comment]
This extension is not maintained anymore. Its not updated since last year. Moreover, its mentioned in the readme itself that some functionality of the site may be lost because of removal of event listeners. 

Another thing I would like to add here, Google Docs is probably using some chrome specific API because voice-typing feature is not yet available on Firefox. I believe that it is the thing that need to be identified and patched in order to make the feature keep working. 

Feel free to modify the code according to your needs. I don't think I will be working over it. :)

**Comment by laminarturbulent** [comment]
For anyone reading this in the future, I found a workaround that achieves (in my opinion) the same functionality. I've discovered two sites so far (speechnotes.co and speechtexter.com) that both seem to use Google's voice typing and give similar, possibly identical results to the Docs voice typing while also letting you dictate even if the window and/or tab are not focused.
